name: Create CSS Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "css"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: input
      id: css-title
      attributes:
          label: The Back Story about your CSS Metaphor
          placeholder: "hint: describe the back story about your css metaphor"
      validations:
          required: true
    - type: textarea
      id: css-content
      attributes:
          label: The CSS Story!
          placeholder: "hint: This is about how a write my css story"
      validations:
          required: true
    - type: input
      id: css-link
      attributes:
          label: A CSS demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: css-donation-link
      attributes:
          label: PayPal Link for Donation (CSS Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
