title: SCP | Metaphor
favicon_ico: "/assets/images/metaphor-square.png"
description: Public Collections of Metaphor our Freestylers accross the world. Gain knowledge with unusual perspective from our Punk members. 
theme: just-the-docs

url: https://streetcommunityprogrammer.github.io/metaphore

aux_links:
  "Our Metaphor": https://github.com/StreetCommunityProgrammer/metaphore

color_scheme: dark
