title: SCP | Metaphor
favicon_ico: "/assets/images/metaphor-square.png"
description: Public Collections of Metaphor our Freestylers accross the world. Gain knowledge with unusual perspective from our Punk members. 
remote_theme: pmarsceill/just-the-docs
baseurl: "/"
url: https://streetcommunityprogrammer.github.io/metaphore

permalink: pretty

aux_links:
  "Our Metaphor": https://github.com/StreetCommunityProgrammer/metaphore

color_scheme: nil

footer_content: "<a href=\"https://github.com/StreetCommunityProgrammer\">Street Community Programmer (SCP)</a> made from Developer ❤️ Developer."

collections:
   stories:
    output: true

just_the_docs:
  collections:
    stories:
      nav_exclude: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - package.json
   - package-lock.json
   - Rakefile
   - LICENSE
   - README.md
   - templates/
   - dist/
