name: Create Golang Story
description: Add this story to the list
title: "Your Story Title"
labels: ["metaphore", "golang"]
assignees: ["darkterminal", "mkubdev"]
body:
    - type: markdown
      attributes:
          value: "**Share the current and relevant details**"
    - type: input
      id: golang-title
      attributes:
          label: The Back Story about your Golang Metaphor
          placeholder: "hint: describe the back story about your golang metaphor"
      validations:
          required: true
    - type: textarea
      id: golang-content
      attributes:
          label: The Golang Story!
          placeholder: "hint: This is about how a write my golang story"
      validations:
          required: true
    - type: input
      id: golang-link
      attributes:
          label: A CSS demo/repos link
          placeholder: "e.g.: https://github.com.com/username/my-repos"
    - type: input
      id: golang-donation-link
      attributes:
          label: PayPal Link for Donation (CSS Storyteller)
          placeholder: "e.g.: https://www.paypal.me/your-paypal-profile-username"
