name: Add a Metaphore
description: Add this metaphore to the list
title: 'Add [METAPHORE NAME]'
labels: ["metaphore"]
body:
  - type: markdown
    attributes:
      value: '**Share the current and relevant details**'
  - type: input
    id: title
    attributes:
      label: Metaphore Name
      placeholder: 'e.g.: Print from a React Native app'
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Metaphore story!
      placeholder: 'To build this automation, i used the websocket library...'
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: A demo/repos link
      placeholder: 'e.g.: https://github.com.com/StreetProgramerCommunity/my-repos'
